wandb_version: 1

config:
  desc: null
  value: null
dataset:
  desc: null
  value: advection_diffusion
seed:
  desc: null
  value: 123
noise_std:
  desc: null
  value: 0.01
learn_noise_std:
  desc: null
  value: 1
optimizer:
  desc: null
  value: adam
print_params:
  desc: null
  value: 0
features:
  desc: null
  value: 0
coeff_inv_std:
  desc: null
  value: 0.0001
n_layers:
  desc: null
  value: 2
use_bias:
  desc: null
  value: 1
non_linear:
  desc: null
  value: 0
dist_weight:
  desc: null
  value: 0
fix_gamma:
  desc: null
  value: 0
gamma_value:
  desc: null
  value: 1.0
log_det_method:
  desc: null
  value: eigvals
n_iterations:
  desc: null
  value: 1000
val_interval:
  desc: null
  value: 100
n_training_samples:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.01
vi_layers:
  desc: null
  value: 1
n_post_samples:
  desc: null
  value: 100
vi_eval:
  desc: null
  value: 0
inference_rtol:
  desc: null
  value: 1.0e-07
plot_vi_samples:
  desc: null
  value: 3
plot_post_samples:
  desc: null
  value: 3
save_pdf:
  desc: null
  value: 1
dump_prediction:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709642277.78966
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 13
      - 16
      - 23
      4: 3.11.4
      5: 0.16.3
      8:
      - 4
      - 5
      13: darwin-arm64
